apiVersion: v1
kind: Service
metadata:
  name: translate-service
spec:
  selector:
    app: translate-app
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: translate-app
spec:
  selector:
    matchLabels:
      app: translate-app
  replicas: 5
  template:
    metadata:
      labels:
        app: translate-app
    spec:
      containers:
      - name: translate-app
        image: mudu_web
        command: python manage.py runserver 0.0.0.0:8001
        ports:
        - containerPort: 5000